"""Generate matching map and highlight geometry from Natural Earth 50m countries.

Usage: python3 scripts/generate-travel-map.py /path/to/ne_50m_admin_0_countries.geojson
Source: https://github.com/nvkelso/natural-earth-vector/blob/master/geojson/ne_50m_admin_0_countries.geojson
Natural Earth data is public domain. No network access is needed by the page.
"""

import json
import sys
from pathlib import Path

ROOT = Path(__file__).resolve().parents[1]



def simplify(points, tolerance=0.08):
    """Retain small islands; simplify each ring within a subpixel tolerance."""
    if len(points) <= 4:
        return points
    start, end = points[0], points[-1]
    dx, dy = end[0] - start[0], end[1] - start[1]
    length = dx * dx + dy * dy
    furthest, distance = 0, 0
    for index, point in enumerate(points[1:-1], 1):
        ratio = max(0, min(1, ((point[0] - start[0]) * dx + (point[1] - start[1]) * dy) / length)) if length else 0
        squared = (point[0] - start[0] - ratio * dx) ** 2 + (point[1] - start[1] - ratio * dy) ** 2
        if squared > distance:
            furthest, distance = index, squared
    if distance <= tolerance * tolerance:
        return [start, end]
    return simplify(points[:furthest + 1], tolerance)[:-1] + simplify(points[furthest:], tolerance)


def shape(geometry):
    polygons = geometry["coordinates"]
    if geometry["type"] == "Polygon":
        polygons = [polygons]
    paths = []
    for polygon in polygons:
        for ring in polygon:
            points = [((longitude + 180) * 2.5, (90 - latitude) * 2.5) for longitude, latitude in ring]
            reduced = simplify(points)
            if len(reduced) < 4:
                reduced = points
            paths.append("M" + "L".join(f"{x:.2f},{y:.2f}" for x, y in reduced) + "Z")
    return "".join(paths)


features = json.loads(Path(sys.argv[1]).read_text())["features"]
shapes = {feature["properties"]["ADMIN"]: shape(feature["geometry"]) for feature in features}

grid = "".join(f'<path d="M{x} 0V450"/>' for x in range(0, 901, 75))
grid += "".join(f'<path d="M0 {y}H900"/>' for y in range(0, 451, 75))
land = "".join(f'<path d="{path}"/>' for path in shapes.values())
svg = '<svg xmlns="http://www.w3.org/2000/svg" viewBox="0 0 900 450">'
svg += '<!-- Natural Earth 50m countries, public domain. Generated by scripts/generate-travel-map.py. -->'
svg += f'<g fill="none" stroke="#bccac6" stroke-width="0.25">{grid}</g>'
svg += f'<g fill="#c1cec6" fill-rule="evenodd" stroke="#a6b7ad" stroke-width="0.1" stroke-linejoin="round">{land}</g></svg>\n'
(ROOT / "public/world-map.svg").write_text(svg)
aliases = {"Türkiye": "Turkey"}
for feature in features:
    properties = feature["properties"]
    for field in ["NAME_EN", "NAME", "NAME_LONG", "ISO_A3", "ADM0_A3"]:
        name = properties.get(field)
        if name and name != "-99" and name not in shapes:
            aliases[name] = properties["ADMIN"]
output = ROOT / "src/data/country-atlas.json"
output.parent.mkdir(exist_ok=True)
output.write_text(json.dumps({"shapes": shapes, "aliases": aliases}, ensure_ascii=False, indent=2) + "\n")

# Editor completion and inline validation for the human-maintained travel record.
place_properties = {
    "id": {"type": "string", "pattern": "^[a-z0-9][a-z0-9-]*$", "description": "Unique identifier, such as tokyo-2027-05. Use a different ID for each return visit."},
    "city": {"type": "string", "minLength": 1, "description": "City or town shown on the page."},
    "country": {"type": "string", "enum": sorted(set(shapes) | {"Türkiye"}), "description": "Country to highlight. Choose a suggested country name."},
    "latitude": {"type": "number", "minimum": -90, "maximum": 90, "description": "Approximate city latitude; negative south of the equator."},
    "longitude": {"type": "number", "minimum": -180, "maximum": 180, "description": "Approximate city longitude; negative west of Greenwich."},
}
visit_properties = {
    **place_properties,
    "month": {"type": "string", "pattern": "^[1-9][0-9]{3}-(0[1-9]|1[0-2])$", "description": "Visit month as YYYY-MM. Future months automatically appear as upcoming."},
    "note": {"type": "string", "description": "Optional short note displayed with the selected visit."},
}
schema = {
    "$schema": "https://json-schema.org/draft/2020-12/schema",
    "title": "Travel record",
    "type": "object",
    "additionalProperties": False,
    "required": ["currentLocation", "visits"],
    "properties": {
        "$schema": {"type": "string"},
        "currentLocation": {"$ref": "#/$defs/place", "description": "Where you are now. Updating visits does not change this."},
        "visits": {"type": "array", "items": {"$ref": "#/$defs/visit"}, "description": "Past visits and future plans. Display order is automatically newest first."},
    },
    "$defs": {
        "place": {"type": "object", "additionalProperties": False, "required": list(place_properties), "properties": place_properties},
        "visit": {"type": "object", "additionalProperties": False, "required": [*place_properties, "month"], "properties": visit_properties},
    },
}
(ROOT / "content/travel.schema.json").write_text(json.dumps(schema, ensure_ascii=False, indent=2) + "\n")
print(f"Generated base map ({len(svg):,} bytes) and {len(shapes)} country shapes for build-time use.")
